I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/level1.rpy", line 477, in script
    $ sanity -= 2
  File "game/level1.rpy", line 477, in <module>
    $ sanity -= 2
NameError: name 'sanity' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/level1.rpy", line 477, in script
    $ sanity -= 2
  File "C:\Users\Indatech\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Indatech\Desktop\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/level1.rpy", line 477, in <module>
    $ sanity -= 2
NameError: name 'sanity' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
It Gazes Back 1.0
Sun Oct  1 20:34:40 2023
